### PR TITLE
Python 3.2 Support...

### PR DESCRIPTION
**Pull request by canardleteer**
Unit tests were failing with tox on 3.2.

I resolved the issues with the six library.

Also added some credits :)

### CODE REVIEW

**Comment by canardleteer** [comment]
It looks like I dumped some of your JSON stuff while I was trying to figure out some Py3 transitional issues. It's still functional & accurate without it, but let me know if you'd prefer the JSON code in the unit tests should remain.

**Comment by ybrs** [comment]
yay :) thank you. and also thanks for adding the credits section in readme, i was going to update the readme and just saw that you already did.

no worries about the JSON code, it was just for tests.

i'll try to add some automated way to run the tests when pushed to repo.

again thanks a lot.

**Comment by canardleteer** [comment]
I think Travis is the "standard way," to add the automated testing, but I don't know how easy it will be to add without a public Disque server that we can point the Unit Tests to use, and with how some of the tests are written, two tests running at the same time may cause some problems.

Until then, I'm just going to test with tox every time I push.

And thank you for writing the lib in the first place!!

**Comment by danudey** [comment]
There's a Travis doc that outlines how to configure your travis.xml file with various options, including how to install custom packages (e.g. redis), install custom software, or run custom scripts: http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by canardleteer** [comment]
Playing with a .travis,yml now, thanks danudey.

ybrs, I may commit one to my fork, but probably won't do a pull request for awhile on it.

**Pull request merged**
