### PR TITLE
I don't trust this...

### PR DESCRIPTION
**Pull request by canardleteer**
This is my first attempt to use Travis-CI, and it's reporting that everything is totally fine. Requesting review and confirmation, or for someone to figure out why things are working a little too well here.

### CODE REVIEW

**Comment by canardleteer** [comment]
Okay, I trust it now. Seems to be working :)

**Comment by ybrs** [comment]
hahah i trust you too, so merging this :)

**Comment by canardleteer** [comment]
It looks like even with contributor access, I cannot add Travis CI to ybrs/pydisque, just canardleteer/pydisque.

So while it works, you'll have to add Travis CI to the master branch (it's just a matter of signing in via GitHub and flicking the switch on the project). The config is already merged, so it should just start running tests and emailing you reports immediately.

**Comment by ybrs** [comment]
I just did, and also added buildstatus icon to readme :)

thank you, for all the work on this.

**Comment by canardleteer** [comment]
Great. Thank you. Now this project looks ever so classy with the build status icon, heh.

I've got a few more unit tests coming in, and I should have some more free time to finish them up later today or tomorrow.

**Pull request merged**
